# MySQL administrator credentials
# This user is used in order to perform tasks related to initialization such as for example
# creating DB schema (see hooks.dbInit)
mysqlAdmin:
    user: "root"
    password: "secret"

# Application environment variables
appEnv:
    # DB_HOST
    dbHost: "mysql"
    # DB_PORT
    dbPort: "3306"
    # DB_USER
    # This value is also used by hooks.dbInit
    dbUser: "admin"
    # DB_PASS
    # This value is also used by hooks.dbInit
    dbPass: "secret"
    # DB_NAME
    dbName: "hasher"